# config/data_paths.yaml
data:
  raw:
    candles: data/raw/market/candles
    news: data/raw/news

  processed:
    features: data/processed/features
    news: data/processed/news
    dataset_tft: data/processed/dataset_tft

  models:
    tft: data/models
